# Site settings
title: Ai Matter Research Group at SDU
email: ahmad.rafsanjani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Transferring great material ideas from Nature to soft robotics.
baseurl:  # the subpath of your site, e.g. /home/
url:  # the base hostname & protocol for your site
twitter_username: rafsanjani84
github_username:  ahmadrafsanjani

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  research:
    output: true
    permalink: /research/:path/
  publication:
    output: true
    permalink: /publication/:path/
